apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockugen-sa
  namespace: dockugen
  labels:
    app: dockugen
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dockugen-role
  labels:
    app: dockugen
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dockugen-role-binding
  labels:
    app: dockugen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dockugen-role
subjects:
- kind: ServiceAccount
  name: dockugen-sa
  namespace: dockugen
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dockugen-namespace-role
  namespace: dockugen
  labels:
    app: dockugen
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dockugen-namespace-role-binding
  namespace: dockugen
  labels:
    app: dockugen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dockugen-namespace-role
subjects:
- kind: ServiceAccount
  name: dockugen-sa
  namespace: dockugen
